version: "3.9"

services:
  auth-service:
    build:
      context: .
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "8030:8030"
    volumes:
      - .:/app

    working_dir: /app
    command: >
      uvicorn auth_service.main:app
      --host 0.0.0.0 --port 8030 --reload
