services:
  db:
    image: postgres:16
    container_name: globalcup_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: globalcup_api
    env_file:
      - .env
    environment:
      # Override DATABASE_URL inside container to point to the docker db
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/app_dev
    depends_on:
      - db
    ports:
      - "8010:8010"
    command: >
      uvicorn API.app.main:app
      --host 0.0.0.0 --port 8010

volumes:
  pgdata:
