version: "3.9"

services:
  servicio-validacion:
    build: .
    container_name: servicio-validacion
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn servicio_validacion.main:app --host 0.0.0.0 --port 8000 --reload

    
