name: test

on:
  push:
    branches:
      - main
      - auth-validation
  pull_request:
    branches:
      - main
      - auth-validation

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint con flake8
        run: |
          flake8 servicio_validacion --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 servicio_validacion --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Ejecutar tests con pytest
        run: |
          pytest tests/unit -v
